version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      trade
      --db-url sqlite:///user_data/tradesv3.sqlite
      --config user_data/config_live.json
      --strategy SniperV5_MathLab